name: Python package tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.10"

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest requests-mock python-dotenv pytest-html

    - name: Set environment variables from GitHub Secrets
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        GOOGLE_CSE_ID: ${{ secrets.GOOGLE_CSE_ID }}
      run: |
        echo "Environment variables set from GitHub Secrets"
        echo "GOOGLE_API_KEY=$GOOGLE_API_KEY" >> .env
        echo "GOOGLE_CSE_ID=$GOOGLE_CSE_ID" >> .env

    - name: Run pytest with HTML report
      run: |
        mkdir -p test-results
        pytest --maxfail=1 --disable-warnings --html=test-results/report.html --self-contained-html

    - name: Upload test report artifact
      uses: actions/upload-artifact@v4
      with:
        name: pytest-report
        path: test-results/report.html
